#pragma config(StandardModel, "Clawbot IQ")
#pragma config(RenamedStdModelMotor, motor1, n)
#pragma config(RenamedStdModelMotor, motor6, m)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{resetMotorEncoder(n);
	resetMotorEncoder(m);
	setMotorTarget( m,3000,100);
	setMotorTarget( n,1500,50);

	waitUntilMotorStop( n);
	waitUntilMotorStop( m);
	resetMotorEncoder(n );
	resetMotorEncoder(m);
	setMotorTarget( m,1500,50);
	setMotorTarget( n,3000,100);

	waitUntilMotorStop( n);
	waitUntilMotorStop( m);



}