#pragma config(Sensor, port2,  touchLED,       sensorVexIQ_LED)
#pragma config(Sensor, port3,  colorDetector,  sensorVexIQ_ColorHue)
#pragma config(Sensor, port4,  gyroSensor,     sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  distanceMM,     sensorVexIQ_Distance)
#pragma config(Sensor, port8,  bumpSwitch,     sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          l,             tmotorVexIQ, openLoop, driveLeft, encoder)
#pragma config(Motor,  motor6,          r,             tmotorVexIQ, openLoop, reversed, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorNone, openLoop)
#pragma config(Motor,  motor11,         clawMotor,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever)

	{
		resetMotorEncoder(r);
 resetMotorEncoder(l);
 setMotorTarget(r,360,
100	);
	setMotorTarget(l,360,
100	);
  waitUntilMotorStop(r);
  waitUntilMotorStop(l);
  }





}
