#pragma config(StandardModel, "VEX IQ Clawbot")
#pragma config(RenamedStdModelMotor, motor1, l)
#pragma config(RenamedStdModelMotor, motor6, r)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		resetMotorEncoder(r);
		resetMotorEncoder(l);
		setMotorTarget(r, 360, 100);
		setMotorTarget(l, 360, 100);
		waitUntilMotorStop(r);
		waitUntilMotorStop(l);
	}
}
