#pragma config(Sensor, port2,  touchLED,       sensorNone)
#pragma config(Sensor, port3,  colorDetector,  sensorNone)
#pragma config(Sensor, port4,  gyroSensor,     sensorNone)
#pragma config(Sensor, port7,  distanceMM,     sensorNone)
#pragma config(Sensor, port8,  bumpSwitch,     sensorNone)
#pragma config(Motor,  motor1,          l,             tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          r,             tmotorVexIQ, PIDControl, driveRight, encoder)
#pragma config(Motor,  motor10,         armMotor,      tmotorNone, openLoop)
#pragma config(Motor,  motor11,         clawMotor,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		resetMotorEncoder(r);
		resetMotorEncoder(l);
		setMotorTarget(r, 360, 100);
		setMotorTarget(l, 360, 100);
		waitUntilMotorStop(r);
		waitUntilMotorStop(l);
	}
}
