#pragma config(Motor,  motor1,          n,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          m,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configurmion wizard               !!*//

task main()
{resetMotorEncoder(n);
 resetMotorEncoder(m);
 setMotorTarget(n,360,
100	);
	setMotorTarget(m,360,
100	);
  waitUntilMotorStop(n)
  waitUntilMotorStop(m);
resetMotorEncoder(n );
resetMotorEncoder(m);
setMotorTarget( m,36000,100);
setMotorTarget( n,18000,50);

waitUntilMotorStop( n);
waitUntilMotorStop( m);


}
