#pragma config(Motor,  motor1,          n,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          m,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{resetMotorEncoder(n);
	resetMotorEncoder(m);
	setMotorTarget( m,3600,100);
	setMotorTarget( n,1800,50);

	waitUntilMotorStop( n);
	waitUntilMotorStop( m);
	resetMotorEncoder(n );
	resetMotorEncoder(m);
	setMotorTarget( m,1800,50);
	setMotorTarget( n,3600,100);

	waitUntilMotorStop( n);
	waitUntilMotorStop( m);



}
