#pragma config(Sensor, port7,  gyroBackup,     sensorVexIQ_Gyro)
#pragma config(Sensor, port8,  gyro,              sensorVexIQ_Gyro)
#pragma config(Sensor, port9,  L,              sensorVexIQ_LED)
#pragma config(Motor,  motor10,         M,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)
{	setTouchLEDColor(L,colorRed);
	if(SensorValue(gyro)>-45&&SensorValue(gyro)<0||SensorValue(gyro)<-315)
{displayTextLine(1,"south");}
	if(SensorValue(gyro)>-135&&SensorValue(gyro)<-45)
{displayTextLine(1,"west");}
	if(SensorValue(gyro)>-225&&SensorValue(gyro)<-135)
{displayTextLine(1,"north");}
	if(SensorValue(gyro)>-315&&SensorValue(gyro)<-225)
{displayTextLine(1,"east");}

	if(SensorValue(gyro)<45&&SensorValue(gyro)>0||SensorValue(gyro)>315)
{displayTextLine(1,"south");}
	if(SensorValue(gyro)<135&&SensorValue(gyro)>45)
{displayTextLine(1,"east");}
	if(SensorValue(gyro)<225&&SensorValue(gyro)>135)
{displayTextLine(1,"north");}
	if(SensorValue(gyro)<315&&SensorValue(gyro)>225)
{displayTextLine(1,"west");}

if(SensorValue(gyro)>5)
{
  setMotorTarget(M,-SensorValue(gyro),30);
  waitUntilMotorStop(M);
}
else if(SensorValue(gyro)<-5)
{
  setMotorTarget(motor10,-SensorValue(gyro),30);
   waitUntilMotorStop(motor10);
}
else
{
	setMotorSpeed(M,0);}
	setTouchLEDColor(L,colorGreen);
}
}
