#pragma config(Sensor, port8,  G,              sensorVexIQ_Gyro)
#pragma config(Sensor, port9,  LED,            sensorVexIQ_LED)
#pragma config(Motor,  motor10,         M,             tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever)
	{
		setMotorTarget(M,-SensorValue(G),30);
waitUntilMotorStop(M);
}



}
