#pragma config(Sensor, port3,  C,              sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{setMotorSpeed(leftMotor,50)
	setMotorSpeed(rightMotor,50)
	sleep(3000)
	repeat (forever) {
		if(getMotorEncoder(motor1)>=3200)
		{
			while(getColorGrayscale(C) >=180) {
				setMotor(leftMotor, 0);
				setMotor(rightMotor, 50);}
			while (getColorGrayscale(C) <=180){
				setMotor(leftMotor,50);
				setMotor(rightMotor, 0);
			}
			setMotorSpeed(leftMotor,50)
			setMotorSpeed(rightMotor,50)
			sleep(10)}

		else{
			while(getColorGrayscale(C) >=180) {
				setMotor(leftMotor, 50);
				setMotor(rightMotor, 0);}
			while (getColorGrayscale(C) <=180){
				setMotor(leftMotor,0);
				setMotor(rightMotor, 50);
			}
			setMotorSpeed(leftMotor,50)
			setMotorSpeed(rightMotor,50)
			sleep(10)
		}



		{



		}
	}



}
