#pragma config(Sensor, port3,  C,              sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	setMotorSpeed(leftMotor, 50);
	setMotorSpeed(rightMotor, 50);
	sleep(3000);

	repeat(forever)
	{
		if(getMotorEncoder(leftMotor) >= 3200)
		{
			while(getColorGrayscale(C) >= 180)
			{
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 50);
			}
			while(getColorGrayscale(C) <= 180)
			{
				setMotorSpeed(leftMotor, 50);
				setMotorSpeed(rightMotor, 0);
			}
		}
		else
		{
			while(getColorGrayscale(C) >= 180)
			{
				setMotorSpeed(leftMotor, 50);
				setMotorSpeed(rightMotor, 0);
			}
			while(getColorGrayscale(C) <= 180)
			{
				setMotorSpeed(leftMotor, 0);
				setMotorSpeed(rightMotor, 50);
			}
		}

		setMotorSpeed(leftMotor, 50);
		setMotorSpeed(rightMotor, 50);
		sleep(10);
	}
}
