#pragma config(Sensor, port11, D,              sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          L,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          R,             tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         G,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		while(getDistanceValue(D)>100)
	{setMotorSpeed(motor1,100);
	 setMotorSpeed(motor6,100);
}
	setMotorSpeed(motor1,50);
	 setMotorSpeed(motor6,-50);
	 }
}
