#pragma config(Sensor, port2,  B1,             sensorVexIQ_Touch)
#pragma config(Sensor, port6,  B2,             sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          M,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int taskCounter = 0;

task one()
{
	setMotorSpeed(M, 50);
	sleep(1000);
	setMotorSpeed(M, 0);
}

task two()
{
	displayTextLine(2, "%d", taskCounter);
	taskCounter++;
}

task main()
{
	int loopCounter = 0;

	repeat(forever)
	{
		if(loopCounter == 59)
		{
			loopCounter = 0;
			displayTextLine(4, "%d", taskCounter);
		}
		else
		{
			loopCounter++;
		}

		startTask(one);
		startTask(two);
		sleep(1000);
	}
}
