#pragma config(Sensor, port2,  B1,             sensorVexIQ_Touch)
#pragma config(Sensor, port6,  B2,             sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          M,             tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task one()
{setMotorSpeed(50,M)
sleep(1000)
}



task two()
{
	int a=0
	displayTextLine(2,"%d",a);
	a++
}



task main()
{

	int b=0
	int a=0
	repeat(forever)
	{
		if(a=59)
	{
		int a=0
		displayTextLine(4,"%d",b);
		b=b+1

		}
		else{}
		startTask(one)
		startTask(two)
	}

}
