#pragma config(Sensor, port1,  G,              sensorVexIQ_Gyro)
#pragma config(Sensor, port2,  D,              sensorVexIQ_Distance)
#pragma config(Sensor, port3,  C,              sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port4,  B,              sensorVexIQ_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever){
	displayTextLine(1,"%d",getColorGrayscale(C));
	displayTextLine(2,"%d",getDistanceValue(D));
	displayTextLine(3,"%d",getGyroDegrees(G));
	displayTextLine(4,"%d",getBumperValue(B));

}}
}
