#pragma config(Sensor, port4,  B,              sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          QR,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor2,          QL,            tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor3,          FS,            tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true)
{if (getJoystickValue(BtnFUp)==1)
	{setMotorSpeed(QR,260);
 setMotorSpeed(QL,260);}
 else
   {setMotorSpeed(QR,0);
 setMotorSpeed(QL,0);}

	if (getJoystickValue(BtnEUp)==1)
	{setMotorSpeed(FS,260);}
	else
	  {setMotorSpeed(FS,0);
	  	}
      }




}
