#pragma config(Sensor, port3,  C,              sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor1,          L,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          R,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int d=0;
	displayTextLine(1,"%d",d)
	repeat(5)
	{
	if(getColorGrayscale(C)<180)
	{setMotorSpeed(L,100)
		setMotorSpeed(R,100)
		sleep(10);}
		else
		{sleep(100);
			d++;
			setMotorSpeed(L,100)
		setMotorSpeed(R,100)
		sleep(1000)
		displayTextLine(1,"%d",d);
	}
}
}

