#pragma config(Sensor, port2,  D,              sensorVexIQ_Distance)
#pragma config(Motor,  motor1,          L,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          R,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat(forever)
{

setMotorSpeed(motor1,70*getJoystickValue(ChA));
 setMotorSpeed(motor4,70*getJoystickValue(ChD));



}


}
