#pragma config(Sensor, port2,  G,              sensorVexIQ_Gyro)
#pragma config(Sensor, port3,  LED,            sensorVexIQ_LED)
#pragma config(Sensor, port5,  L,              sensorVexIQ_LED)
#pragma config(Sensor, port6,  T,              sensorVexIQ_LED)
#pragma config(Motor,  motor1,          L,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor4,          R,             tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{	while(true)
{if(getJoystickValue(BtnEUp)==1)
	{
		setMotorSpeed(L,-100);
		setMotorSpeed(R,100);
	}
	else if(getJoystickValue(BtnFUp)==1)
	{setMotorSpeed(R,-100);
		setMotorSpeed(L,100);
	}
	else if(getJoystickValue(BtnLUp)==1)
	{setMotorSpeed(L,getJoystickValue(ChA));
	 setMotorSpeed(R,getJoystickValue(ChA));}


  else{setMotorSpeed(R,0);
		setMotorSpeed(L,0);
	}

  }
}
