#pragma config(Sensor, port7,  B,              sensorVexIQ_Touch)
#pragma config(Motor,  motor8,          M,             tmotorVexIQ, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		while(getBumperValue(B) == 1)
		{
			setMotorSpeed(M, 100);
		}
		setMotorSpeed(M, 0);
	}
}
