#pragma config(Sensor, port7,  B,              sensorVexIQ_Touch)
#pragma config(Motor,  motor8,          M,             tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{repeat (forever)
	{while(getBumperValue(port7)==1)
	{setMotorSpeed(motor8,127);}
    setMotorSpeed(motor8,0);}}
