#pragma config(Sensor, port4,  B1,             sensorVexIQ_Touch)
#pragma config(Sensor, port5,  B2,             sensorVexIQ_Touch)
#pragma config(Motor,  motor1,          L,             tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor3,          Z2,            tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor6,          R,             tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor8,          Z1,            tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor9,          Buo1,          tmotorVexIQ, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{setMotorSpeed(motor1,50);
	setMotorSpeed(motor6,50);
	sleep(2500);
setMotorSpeed(motor1,50);
setMotorSpeed(motor6,-50);
sleep(1000);
repeat(20)
{
	resetMotorEncoder(motor9);
	setMotorSpeed(motor6,0);
	setMotorSpeed(motor1,0);
	while(getBumperValue(B1)==0)
{
setMotorSpeed(motor8,100);
setMotorSpeed(motor3,100);
}
setMotorSpeed(motor8,100);
setMotorSpeed(motor3,100);
setMotorTarget(motor9,-360,100);



	}
setMotorSpeed(motor1,-50);
	setMotorSpeed(motor6,-50);
	sleep(2500);
setMotorSpeed(motor1,-50);
setMotorSpeed(motor6,50);
sleep(1000);


}
