#pragma config(Sensor, port7,  LED1,           sensorVexIQ_LED)
#pragma config(Sensor, port8,  LED2,           sensorVexIQ_LED)
#pragma config(Sensor, port9,  B,              sensorVexIQ_Touch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		if(getBumperValue(B) == 1)
		{
			setTouchLEDColor(LED1, colorRed);
			setTouchLEDColor(LED2, colorGreen);
			sleep(6500);
			setTouchLEDColor(LED1, colorRed);
			setTouchLEDColor(LED2, colorYellow);
			sleep(2000);
			setTouchLEDColor(LED1, colorGreen);
			setTouchLEDColor(LED2, colorRed);
			sleep(6500);
			setTouchLEDColor(LED1, colorYellow);
			setTouchLEDColor(LED2, colorRed);
			sleep(2000);
		}
		else
		{
			setTouchLEDColor(LED1, colorBlue);
			setTouchLEDColor(LED2, colorBlue);
			sleep(100);
		}
	}
}
