#pragma config(Sensor, port1,  LED1,           sensorVexIQ_LED)
#pragma config(Sensor, port2,  LED2,           sensorVexIQ_LED)
#pragma config(Sensor, port5,  LED3,           sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

		while(getTouchLEDValue(LED2)==0);
		{
			setTouchLEDColor(LED2,colorRed);
			sleep(100);
			}
			while(getTouchLEDValue(LED2)==0);
		{
			setTouchLEDColor(LED2,colorGreen);
			sleep(100);
			}
					while(getTouchLEDValue(LED2)==0)
		{setTouchLEDColor(LED2,colorBlue);
			sleep(100);
			}


}
