#pragma config(Sensor, port1,  LED1,           sensorVexIQ_LED)
#pragma config(Sensor, port2,  LED2,           sensorVexIQ_LED)
#pragma config(Sensor, port5,  LED3,           sensorVexIQ_LED)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever)
	{
		setTouchLEDColor(LED1, colorRed);
		sleep(1000);
		setTouchLEDColor(LED2, colorYellow);
		setTouchLEDColor(LED1, colorRed);
		sleep(1000);
		setTouchLEDColor(LED3, colorGreen);
		setTouchLEDColor(LED2, colorYellow);
		setTouchLEDColor(LED1, colorRed);
		sleep(1000);
	}
}
